### ISSUE TITLE
Quiz Quiz 3 (Ch.6) - Jan 22

### ISSUE THREAD

**Issue by JasperC3** [JasperC3/Stuff#16]

**Comment by pjcpjc** [comment]
The title for this should be Jan 22. The time can be in the description. @JasperC3

**Comment by pjcpjc** [comment]
@JasperC3  is this done or what? If done, close it with some notes on what you remember from doing it.

**Comment by JasperC3** [comment]
I did this quiz around 2pm or so. It was pretty easy, got 20/20 (it was online, of course)
