### ISSUE TITLE
HW #1: Five linguistic features-- Jan 15

### ISSUE THREAD

**Issue by JasperC3** [JasperC3/Stuff#6]
https://canvas.uoregon.edu/courses/192601/modules/items/3403681

**Comment by pjcpjc** [comment]
This is now late. Professor said he will still accept. Hand it on by Sunday Jan 24. @JasperC3

**Comment by JasperC3** [comment]
HW #1 turned in, not yet graded. Turned it in online, extra copy is in the google drive.
